package br.com.tcc.view;

import br.com.tcc.service.ComparaTabela;
import br.com.tcc.bean.Conexao;
import br.com.tcc.principal.AbaConexaoTopComponent;
import br.com.tcc.service.ComparaColuna;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//br.com.tcc.view//Compara//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "ComparaTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "br.com.tcc.view.ComparaTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ComparaAction",
        preferredID = "ComparaTopComponent")
@Messages({
    "CTL_ComparaAction=Compara",
    "CTL_ComparaTopComponent=Compara Window",
    "HINT_ComparaTopComponent=This is a Compara window"
})
public final class ComparaTopComponent extends TopComponent {

    public ComparaTopComponent() {
        initComponents();
        setName(Bundle.CTL_ComparaTopComponent());
        setToolTipText(Bundle.HINT_ComparaTopComponent());
        loadCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbBaseAntiga = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbBaseAtual = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextPane();
        btComparar = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ComparaTopComponent.class, "ComparaTopComponent.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ComparaTopComponent.class, "ComparaTopComponent.jLabel2.text")); // NOI18N

        txtArea.setEditable(false);
        txtArea.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(txtArea);

        org.openide.awt.Mnemonics.setLocalizedText(btComparar, org.openide.util.NbBundle.getMessage(ComparaTopComponent.class, "ComparaTopComponent.btComparar.text")); // NOI18N
        btComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbBaseAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbBaseAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btComparar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBaseAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBaseAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btComparar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompararActionPerformed
        if (valida()) {
            ComparaTabela comparaTabela = new ComparaTabela();
            Conexao conexaoAntiga = (Conexao) cmbBaseAntiga.getSelectedItem();
            Conexao conexaoAtual = (Conexao) cmbBaseAtual.getSelectedItem();
            ComparaColuna comparaColuna = new ComparaColuna(conexaoAntiga, conexaoAtual);
            String resultado = comparaTabela.comparaNome(conexaoAntiga, conexaoAtual);
//            resultado += comparaColuna.comparaNome(conexaoAntiga, conexaoAtual);
            txtArea.setText(resultado);
        }
    }//GEN-LAST:event_btCompararActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComparar;
    private javax.swing.JComboBox cmbBaseAntiga;
    private javax.swing.JComboBox cmbBaseAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void loadCombo() {
        List<Conexao> lista = AbaConexaoTopComponent.lista;
        DefaultComboBoxModel dbm = (DefaultComboBoxModel) cmbBaseAntiga.getModel();
        DefaultComboBoxModel dcm = (DefaultComboBoxModel) cmbBaseAtual.getModel();
        for (Conexao conexao : lista) {
            dbm.addElement(conexao);
            dcm.addElement(conexao);
        }

    }

    private boolean valida() {
        if (cmbBaseAntiga.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Deve ser selecionada a base antiga", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (cmbBaseAtual.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Deve ser selecionada a base atual", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;

    }
}
